Repository insightsengineering/chevron, pull requests merged in 2023-12, with the labels that each got.

#707 Update MNG01 test snapshots
  tests/testthat/_snaps/mng01/mng01-with-custom-theme.svg
  tests/testthat/_snaps/mng01/mng01-with-default-value.svg
  tests/testthat/_snaps/mng01/run-mng01-with-combination-of-x-variables.svg
  tests/testthat/_snaps/mng01/run-mng01-with-custom-color-set.svg
  tests/testthat/_snaps/mng01/run-mng01-with-custom-unnamed-color-set.svg
  tests/testthat/_snaps/mng01/run-mng01-with-jitter.svg
  tests/testthat/_snaps/mng01/run-mng01-with-numeric-x-variables.svg
Labels: sme

#711 708 DMT01 issue with single summaryvars
  R/dmt01.R
  tests/testthat/_snaps/dmt01.md
  tests/testthat/test-dmt01.R
Labels: chevron

#710 adapt function and set option
  DESCRIPTION
  NEWS.md
  R/rtables_utils.R
  R/ttet01.R
  R/utils.R
  R/zzz.R
  man/h_format_dec.Rd
  tests/testthat/_snaps/aet05.md
  tests/testthat/_snaps/aet05_all.md
Labels: chevron

#694 693 Priority order in run method
  NEWS.md
  R/chevron_tlg-S4methods.R
  tests/testthat/_snaps/chevron_tlg-methods.md
  tests/testthat/test-chevron_tlg-methods.R
Labels: chevron

#582 Adds min package version
  .github/workflows/scheduled.yml
  DESCRIPTION
  NEWS.md
Labels: core
