Repository insightsengineering/chevron, pull requests merged in 2024-03, with the labels that each got.

#731 skip_on_ci
  NEWS.md
  R/dmt01.R
  tests/testthat/test-dmt01.R
  tests/testthat/test-mng01.R
Labels: chevron

#733 Update `kmg01` usage after `g_km` refactor
  DESCRIPTION
  R/kmg01.R
  man/kmg01.Rd
  tests/testthat/test-kmg01.R
  vignettes/chevron_catalog.rmd
Labels: sme

#720 strict tests; minor enhancements
  NEWS.md
  R/fstg01.R
  R/fstg02.R
  R/kmg01.R
  R/mng01.R
  man/kmg01.Rd
  tests/testthat/setup-options.R
  tests/testthat/test-chevron_tlg-methods.R
  tests/testthat/test-kmg01.R
  vignettes/chevron_catalog.rmd
Labels: sme, chevron
