Repository insightsengineering/chevron, pull requests merged in 2024-06, with the labels that each got.

#755 update snapshots
  tests/testthat/_snaps/ael02.md
  tests/testthat/_snaps/ael03.md
  tests/testthat/test-ael02.R
  tests/testthat/test-ael03.R
  tests/testthat/test-utils.R
Labels: chevron

#751 Bumps `{rmarkdown}` minimal version
  DESCRIPTION
Labels: core

#757 Update DESCRIPTION
  DESCRIPTION
Labels: sme, chevron

#759 758 improve null report
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/ael01_nollt.R
  R/aet01.R
  R/aet01_aesi.R
  R/aet02.R
  R/aet03.R
  R/aet04.R
  R/aet05.R
  R/aet10.R
  R/cfbt01.R
  R/chevron_tlg-S4class.R
  R/cmt01a.R
  R/coxt01.R
  R/dmt01.R
  R/dst01.R
  R/dtht01.R
  R/egt02.R
  R/egt03.R
  R/egt05_qtcat.R
  R/ext01.R
  R/lbt04.R
  R/lbt05.R
  R/lbt06.R
  R/lbt07.R
  R/lbt14.R
  R/mht01.R
  R/pdt01.R
  R/pdt02.R
  R/report_null.R
  R/rmpt01.R
  R/rmpt06.R
  R/rspt01.R
  R/rtables_utils.R
  R/ttet01.R
  R/utils.R
  R/vst02.R
  _pkgdown.yaml
  man/ael01_nollt.Rd
  man/chevron_tlg-class.Rd
  man/report_null.Rd
  man/std_postprocess.Rd
  man/std_postprocessing.Rd
  tests/testthat/_snaps/lbt06.md
  tests/testthat/test-default_tlg.R
  tests/testthat/test-empty_report.R
  tests/testthat/test-lbt06.R
  tests/testthat/test-report_null.R
Labels: chevron
