Repository insightsengineering/chevron, pull requests merged in 2025-01, with the labels that each got.

#805 804 ttet01 fails with empty level in arm_var
  NEWS.md
  R/ttet01.R
  tests/testthat/test-ttet01.R
Labels: chevron

#806 Update DESCRIPTION
  DESCRIPTION
Labels: sme

#808 Fix class error@main
  NEWS.md
  R/lbt04.R
  R/lbt05.R
  tests/testthat/_snaps/lbt05.md
  tests/testthat/test-lbt05.R
Labels: bug, chevron
