Repository insightsengineering/chevron, pull requests merged in 2025-02, with the labels that each got.

#810 809 adjust default precision@main
  NAMESPACE
  NEWS.md
  R/cfbt01.R
  R/egt01.R
  R/lbt01.R
  R/vst01.R
  _pkgdown.yaml
  man/afun_skip.Rd
  man/cfbt01.Rd
  man/cfbt01_lyt.Rd
  man/egt01.Rd
  man/lbt01.Rd
  man/vst01.Rd
  tests/testthat/_snaps/egt01.md
  tests/testthat/_snaps/lbt01.md
  tests/testthat/_snaps/vst01.md
  tests/testthat/test-egt01.R
  tests/testthat/test-lbt01.R
  tests/testthat/test-vst01.R
Labels: chevron

#813 [skip vbump] release 0.2.9
  DESCRIPTION
  NEWS.md
Labels: chevron

#821 Update test-utils.R
  tests/testthat/test-utils.R
Labels: sme, chevron

#815 Remove lookup-refs
  .github/workflows/check.yaml
  .github/workflows/docs.yaml
  .github/workflows/scheduled.yaml
Labels: core

#822 Update DESCRIPTION
  DESCRIPTION
  chevron.Rproj
  man/chevron-package.Rd
Labels: sme
